import { themes as prismThemes } from "prism-react-renderer";
import type { Config } from "@docusaurus/types";
import type * as Preset from "@docusaurus/preset-classic";

// Redirects are generated by the migration script and imported here.
// This file is auto-generated — see scripts/migrate-gitbook.mjs
import { redirects } from "./redirects";

const config: Config = {
  title: "Trunk Docs",
  tagline: "Ship Software as Fast as AI Writes It",
  favicon: "img/favicon.ico",

  url: "https://samgutentag.github.io",
  baseUrl: "/trunk-docs-docusaurus/",

  organizationName: "samgutentag",
  projectName: "trunk-docs-docusaurus",

  onBrokenLinks: "warn",
  onBrokenMarkdownLinks: "warn",
  onBrokenAnchors: "warn",

  markdown: {
    format: "detect",
    mdx1Compat: {
      comments: true,
      admonitions: true,
      headingIds: true,
    },
    hooks: {
      onBrokenMarkdownImages: "warn",
    },
  },

  i18n: {
    defaultLocale: "en",
    locales: ["en"],
  },

  presets: [
    [
      "classic",
      {
        docs: {
          routeBasePath: "/",
          sidebarPath: "./sidebars.ts",
          editUrl: "https://github.com/trunk-io/docs/edit/main/",
        },
        blog: false,
        theme: {
          customCss: "./src/css/custom.css",
        },
      } satisfies Preset.Options,
    ],
  ],

  plugins: [
    [
      "@docusaurus/plugin-client-redirects",
      {
        redirects,
      },
    ],
  ],

  themeConfig: {
    navbar: {
      title: "Trunk Docs",
      logo: {
        alt: "Trunk Logo",
        src: "img/logo.svg",
      },
      items: [
        {
          href: "https://app.trunk.io",
          label: "Open App",
          position: "right",
        },
        {
          href: "https://slack.trunk.io",
          label: "Community",
          position: "right",
        },
      ],
    },
    footer: {
      style: "dark",
      links: [
        {
          title: "Products",
          items: [
            { label: "Merge Queue", to: "/merge-queue/" },
            { label: "Flaky Tests", to: "/flaky-tests/overview" },
          ],
        },
        {
          title: "Community",
          items: [
            { label: "Slack", href: "https://slack.trunk.io" },
            { label: "Changelog", href: "https://trunk.io/changelog" },
            {
              label: "Feature Requests",
              href: "https://features.trunk.io",
            },
          ],
        },
        {
          title: "More",
          items: [
            { label: "trunk.io", href: "https://trunk.io" },
            { label: "GitHub", href: "https://github.com/trunk-io" },
          ],
        },
      ],
      copyright: `Copyright \u00a9 ${new Date().getFullYear()} Trunk Technologies, Inc.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: [
        "bash",
        "json",
        "yaml",
        "toml",
        "ruby",
        "python",
        "java",
        "kotlin",
        "swift",
        "rust",
        "go",
        "csharp",
        "php",
        "groovy",
        "dart",
      ],
    },
    algolia: {
      // Apply for DocSearch at https://docsearch.algolia.com/apply/
      // Or use your own Algolia crawler
      appId: "YOUR_APP_ID",
      apiKey: "YOUR_SEARCH_ONLY_API_KEY",
      indexName: "trunk-docs",
      contextualSearch: true,
      searchPagePath: "search",
    },
    colorMode: {
      defaultMode: "light",
      disableSwitch: false,
      respectPrefersColorScheme: true,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
